# Generated by Django 3.0.7 on 2020-09-01 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('course_content_one', models.TextField()),
                ('course_content_two', models.TextField(null=True)),
                ('course_content_three', models.TextField(null=True)),
                ('course_content_four', models.TextField(null=True)),
                ('course_content_five', models.TextField(null=True)),
                ('date', models.DateField()),
                ('duration', models.IntegerField(help_text='Enter number of hours', null=True)),
                ('video1_url', models.CharField(max_length=255, null=True)),
                ('video2_url', models.CharField(max_length=255, null=True)),
                ('video3_url', models.CharField(max_length=255, null=True)),
                ('resource1_url', models.CharField(max_length=255, null=True)),
                ('resource2_url', models.CharField(max_length=255, null=True)),
                ('resource3_url', models.CharField(max_length=255, null=True)),
                ('is_required', models.BooleanField(default=True, null=True)),
            ],
        ),
    ]
