# Generated by Django 3.0.7 on 2020-08-21 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('course_content_one', models.CharField(max_length=300)),
                ('course_content_two', models.CharField(max_length=300)),
                ('course_content_three', models.CharField(max_length=300)),
                ('date', models.DateField()),
                ('duration', models.IntegerField(help_text='Enter number of hours')),
                ('video_url', models.CharField(max_length=255)),
                ('resource_url', models.CharField(max_length=255)),
                ('is_required', models.BooleanField(default=True)),
            ],
        ),
    ]
