# Generated by Django 3.0.7 on 2020-09-13 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='resource1_url',
            new_name='resource_url',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='resource2_url',
            new_name='video_url',
        ),
        migrations.RemoveField(
            model_name='course',
            name='video1_url',
        ),
        migrations.RemoveField(
            model_name='course',
            name='video2_url',
        ),
    ]
