# Generated by Django 3.0.7 on 2020-08-26 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20200826_1340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='resource_url',
            new_name='resource1_url',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='video_url',
            new_name='resource2_url',
        ),
        migrations.AddField(
            model_name='course',
            name='resource3_url',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='video1_url',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='video2_url',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='video3_url',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
