# Generated by Django 3.1 on 2020-08-20 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='preferred_name',
        ),
    ]
