# Generated by Django 3.0.7 on 2020-08-25 18:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_student_badge'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='facebook_address',
            field=models.CharField(default=django.utils.timezone.now, max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='linkedIn_address',
            field=models.CharField(default=django.utils.timezone.now, max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='location',
            field=models.CharField(default=django.utils.timezone.now, max_length=60),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='student_type',
            field=models.CharField(default='individual', max_length=15),
        ),
    ]
