# Generated by Django 3.0.7 on 2020-09-23 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200923_1216'),
        ('users', '0003_auto_20200920_1616'),
    ]

    operations = [
    ]
