# Generated by Django 3.0.7 on 2020-08-27 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_firstname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='user',
            name='lastname',
        ),
    ]
