# Generated by Django 3.0.7 on 2020-09-11 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course_Modules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('module_overview', models.TextField()),
                ('module_content_one', models.TextField(null=True)),
                ('module_content_two', models.TextField(null=True)),
                ('duration', models.IntegerField(help_text='Enter number of hours', null=True)),
                ('video1_url', models.CharField(max_length=255, null=True)),
                ('resource1_url', models.CharField(max_length=255, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course')),
            ],
        ),
    ]
