# Generated by Django 3.0.7 on 2020-09-23 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course_Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('module_number', models.IntegerField(unique=True)),
                ('module_overview', models.TextField()),
                ('content_one', models.TextField(blank=True, null=True)),
                ('content_two', models.TextField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, help_text='Enter number of hours', null=True)),
                ('video_url', models.CharField(blank=True, max_length=255, null=True)),
                ('resource_url', models.CharField(blank=True, max_length=255, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='courses.Course')),
            ],
            options={
                'ordering': ['module_number'],
                'unique_together': {('course', 'title')},
            },
        ),
    ]
