# Generated by Django 3.0.7 on 2020-09-12 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_modules', '0002_auto_20200912_1606'),
        ('lessons', '0004_auto_20200912_1606'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course_Modules',
        ),
        migrations.AddField(
            model_name='course_module',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='courses.Course'),
        ),
        migrations.AlterUniqueTogether(
            name='course_module',
            unique_together={('course', 'title')},
        ),
    ]
