# Generated by Django 3.0.7 on 2020-09-11 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course_modules', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('order_number', models.IntegerField(unique=True)),
                ('lesson_content_one', models.TextField()),
                ('lesson_content_two', models.TextField(null=True)),
                ('lesson_content_three', models.TextField(null=True)),
                ('date', models.DateField(null=True)),
                ('duration', models.IntegerField(help_text='Enter number of hours', null=True)),
                ('video1_url', models.CharField(max_length=255, null=True)),
                ('video2_url', models.CharField(max_length=255, null=True)),
                ('resource1_url', models.CharField(max_length=255, null=True)),
                ('resource2_url', models.CharField(max_length=255, null=True)),
                ('course_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_modules.Course_Modules')),
            ],
            options={
                'ordering': ['order_number'],
            },
        ),
    ]
