# Generated by Django 3.0.7 on 2021-01-06 21:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course_modules', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('lesson_number', models.IntegerField(unique=True)),
                ('content_one', models.TextField()),
                ('content_two', models.TextField(blank=True, null=True)),
                ('content_three', models.TextField(blank=True, null=True)),
                ('date', models.DateField(null=True)),
                ('duration', models.IntegerField(help_text='Enter number of hours', null=True)),
                ('video_one', models.CharField(max_length=255, null=True)),
                ('video_two', models.CharField(blank=True, max_length=255, null=True)),
                ('resource_url', models.CharField(max_length=255, null=True)),
                ('course_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='course_modules.Course_Module')),
            ],
            options={
                'ordering': ['lesson_number'],
                'unique_together': {('course_module', 'title')},
            },
        ),
        migrations.CreateModel(
            name='Lesson_Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.Lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
