# Generated by Django 3.0.7 on 2020-09-12 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_modules', '0001_initial'),
        ('lessons', '0002_auto_20200912_0813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='course_module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='course_modules.Course_Modules'),
        ),
    ]
