# Generated by Django 3.0.7 on 2020-10-06 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_modules', '0001_initial'),
        ('lessons', '0002_lesson_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='status',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='status', to='course_modules.Course_Module'),
            preserve_default=False,
        ),
    ]
