# Generated by Django 3.0.7 on 2020-09-12 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_modules', '0002_auto_20200912_1606'),
        ('lessons', '0003_auto_20200912_1516'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['lesson_number']},
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='lesson_content_one',
            new_name='content_one',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='order_number',
            new_name='lesson_number',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='resource1_url',
            new_name='resource_url',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='resource2_url',
            new_name='video_one',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='lesson_content_three',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='lesson_content_two',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='video1_url',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='video2_url',
        ),
        migrations.AddField(
            model_name='lesson',
            name='content_three',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='content_two',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='video_two',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='course_module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='course_modules.Course_Module'),
        ),
    ]
