# Generated by Django 3.0.7 on 2020-10-07 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0005_auto_20201007_0524'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson_status',
            old_name='student',
            new_name='user',
        ),
    ]
