# Generated by Django 3.0.7 on 2020-09-29 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice_test', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='label',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='question',
            name='label',
            field=models.TextField(),
        ),
    ]
