# Generated by Django 3.0.7 on 2020-11-05 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice_test', '0002_auto_20200929_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiztaker',
            name='percentage',
            field=models.IntegerField(default=0),
        ),
    ]
