# Generated by Django 3.0.7 on 2020-09-23 05:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('practice_test', '0002_auto_20200922_1746'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ['timestamp'], 'verbose_name_plural': 'Quizzes'},
        ),
        migrations.RenameField(
            model_name='quiztaker',
            old_name='correct_answers',
            new_name='score',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='text',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='created',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='questions_count',
        ),
        migrations.AddField(
            model_name='answer',
            name='label',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiztaker',
            name='date_finished',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='label',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='slug',
            field=models.SlugField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Response',
        ),
        migrations.AddField(
            model_name='usersanswer',
            name='answer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='practice_test.Answer'),
        ),
        migrations.AddField(
            model_name='usersanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practice_test.Question'),
        ),
        migrations.AddField(
            model_name='usersanswer',
            name='quiz_taker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practice_test.QuizTaker'),
        ),
    ]
