# Generated by Django 3.0.7 on 2021-01-19 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice_test', '0004_quiztaker_total_quizzes_taken'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiztaker',
            name='avg_quiz_score',
            field=models.IntegerField(default=0),
        ),
    ]
